# This is a basic workflow to help you get started with Actions
name: EC2 Deploy
on:
  # Triggers the workflow on push or pull request events but only for the "trunk" branch
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]
  workflow_dispatch:
    inputs:
      Instance-ID:
        required: true
        type: string
      Region:
        required: true
        type: choice
        options:
        - us-east-2
        - us-east-1
        - us-west-1	
        - us-west-2
#      deploy_target:
#        required: true
#        type: string
#      perform_deploy:
#        required: true
#        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    # if: ${{ inputs.perform_deploy }}
    steps:
      - name: Run EC2 Instance
        run: echo "Deploying build:${{ inputs.Region }} to target:${{ inputs.Instance-ID }}"
        
